### PR TITLE
Update to packaging URL

### PR DESCRIPTION
**Pull request by taniarichardsonoctopus**
To help understand our users, we want to see how many are viewing the docs by clicking on a link in product.  This will help us understand whether our contextual help is providing enough information, or if something isn't clear.  We're starting with 'Packaging'.

### CODE REVIEW

**Comment by taniarichardsonoctopus** [comment]
Creating a new branch for this one.

**Comment by taniarichardsonoctopus** [comment]
@thebigmoosey  I'd forgotten to merge this one.  Could you please see why the check is failing before I merge this?  Thanks

**Comment by thebigmoosey** [comment]
@taniarichardsonoctopus Was just a blip in the TeamCity build apparently, I merged latest and all looks ok :) Will leave the merge to you

**Comment by taniarichardsonoctopus** [comment]
thanks, merging.

**Pull request merged**
